In [ ]:
# Input temperature in Celsius
celsius = float(input("Enter temperature in Celsius: "))

# Convert to Fahrenheit
fahrenheit = celsius * (9 / 5) + 32

# Output the result
print(f"{celsius}°C is equal to {fahrenheit}°F.")


Enter temperature in Celsius: 25
25.0°C is equal to 77.0°F.


In [ ]:
#Create one variable for carbon footprint
carbon_footprint = 500.75
print (f"Carbon Footprint: {carbon_footprint} kg CO2")


Carbon Footprint: 500.75 kg CO2


In [ ]:
is_sustainable = carbon_footprint < 400
print (f"Is the city sustainable? {is_sustainable}")

Is the city sustainable? False


In [ ]:
#use identity operator to know if the given input is digit or not (use input)
a=input("Enter a value: ")
if a.isdigit():
    print("It is a digit.")
else:
    print("Not a digit.")

Enter a value: 200
It is a digit.


In [ ]:
#write a list and check if any input element is present in that list or not
list_1=[1,2,"Asita",111]
b=input("Enter an element: ")
if b in list_1:
    print("Element is in list.")
else:
    print("Element is not in list.")

Enter an element: 200
Element is not in list.


In [ ]:
#Create a simple calculator using if, elif and else
a=float(input("Enter value of a: "))
b=float(input("Enter value of b: "))
ope=input("Enter the operator: ")
if ope == "+":
    print("Value of a+b is: ",a+b)
elif ope == "-":
    print("Value of a-b is: ",a-b)
elif ope == "*":
    print("Value of a*b is: ",a*b)
else:
    print("Value of a/b is: ",a/b)

Enter value of a: 200
Enter value of b: 300
Enter the operator: +
Value of a+b is:  500.0


In [ ]:
#Write for loop to filter out the cities with high temperature
climate_data = [
    {"city": "City A", "temperature": 25, "carbon_footprint": 500},
    {"city": "City B", "temperature": 30, "carbon_footprint": 350},
    {"city": "City C", "temperature": 22, "carbon_footprint": 600},
    {"city": "City D", "temperature": 15, "carbon_footprint": 200},
    {"city": "City E", "temperature": 28, "carbon_footprint": 450},
]
#high temperature threshold (Cities above this temperature will be selected)
high_temp_threshold = 26
#use a list comprehension to filter cities with temperature higher than the threshold
high_temp_cities = [city for city in climate_data if city["temperature"] > high_temp_threshold]
#print the result
print("Cities with high temperature (> 26 degree C): ")
for city in high_temp_cities:
    print(f"{city['city']}-{city['temperature']} degree C")

Cities with high temperature (> 26 degree C): 
City B-30 degree C
City E-28 degree C


In [ ]:
#initialize a variabel to store the total carbon footprint
total_carbon=0
#use a for loop to go through each city is the dataset and add their carbon footprint
for city in climate_data:
    total_carbon += city["carbon_footprint"] # add each city's carbon footprint in the total

#calculate the average carbon footprint
average_carbon_footprint=total_carbon/len(climate_data)

#print the average result
print(f"\n Average Carbon Footprint: {average_carbon_footprint:.2f} kg CO2")


 Average Carbon Footprint: 420.00 kg CO2


In [ ]:
def add(a, b):
    c = a + b
    return c

In [ ]:
add(3,4)
z = 5
print(z)

5


In [ ]:
y = lambda x : x + 2
print(y(2))

4


In [ ]:
# Use max() to find the city with the highest carbon footprint
highest_footprint_city = max(climate_data, key=lambda city: city["carbon_footprint"])

# Print the result
print(f"{highest_footprint_city['city']} - {highest_footprint_city['carbon_footprint']} kg CO2")


City C - 600 kg CO2


In [ ]:
#write a function which will take two parameters energy consumption, energy factor and give the carbon footprint
# Define variables for energy consumption and emission factor
energy_consumption = 1000  # in kWh
emission_factor = 8.475  # kg CO2 per kWh

# Define the function to calculate carbon footprint
def calculate_carbon_footprint(energy_consumption, emission_factor):
    carbon_footprint = energy_consumption * emission_factor
    return carbon_footprint

# Calculate and print the carbon footprint
carbon_footprint = calculate_carbon_footprint(energy_consumption, emission_factor)
print(f"Carbon Footprint: {carbon_footprint} kg CO2")

Carbon Footprint: 8475.0 kg CO2


In [ ]:
# Sustainability threshold
sustainability_threshold = 400

# Filtering sustainable cities
sustainable_cities = list(filter(lambda city: city['carbon_footprint'] < sustainability_threshold, climate_data))

# Printing the filtered list of sustainable cities
print("Sustainable Cities: ")
for city in sustainable_cities:
    print(city["city"])

Sustainable Cities: 
City B
City D


In [ ]:
#use lambda function to find if a year is leap year or not
ly = lambda year: (year % 4 == 0 and year % 100 != 0) or (year % 400 == 0)

year = int(input("Enter a year: "))
print(f"{year} is a leap year." if ly(year) else f"{year} is not a leap year.")

Enter a year: 2004
2004 is a leap year.


Series, DataFrames and Basic Operations

In [ ]:
import pandas as pd

#sample renew energy sources data
renew_sources=["Solar","Wind","Hydro","Geothermal","Biomass"]

#sample green tech proj data (for data frame)
data = {
    "Project": ["Solar Farm A", "Wind Turbine X", "Hydropower Y", "Solar Roof Z", "Geothermal Plant P"],
    "Technology": ["Solar", "Wind", "Hydropower", "Solar", "Geothermal"],
    "Capacity (MW)": [150, 300, 200, 50, 100],  # Megawatts
    "Cost (Million $)": [200, 400, 350, 100, 250],  # Project cost
    "Location": ["California", "Texas", "Washington", "Nevada", "Idaho"],
    "Completion Year": [2023, 2024, 2022, 2025, 2023]
}

In [ ]:
renewable_series = pd.Series(renew_sources)

print("Renewable Energy Sources:")
print(renewable_series)

Renewable Energy Sources:
0         Solar
1          Wind
2         Hydro
3    Geothermal
4       Biomass
dtype: object


In [ ]:
projects_df = pd.DataFrame(data)

projects_df.head()
#print the dataframe
#print("\nGreen Technology Projects Dataframe:")
#print(projects_df)

Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  
0  California             2023  
1       Texas             2024  
2  Washington             2022  
3      Nevada             2025  
4       Idaho             2023

In [ ]:
#code to get only second and the third data
projects_df.loc[1:3]


Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   
3    Solar Roof Z       Solar             50               100      Nevada   

   Completion Year  
1             2024  
2             2022  
3             2025

In [ ]:
projects_df.describe()

Capacity (MW)  Cost (Million $)  Completion Year
count        5.00000          5.000000         5.000000
mean       160.00000        260.000000      2023.400000
std         96.17692        119.373364         1.140175
min         50.00000        100.000000      2022.000000
25%        100.00000        200.000000      2023.000000
50%        150.00000        250.000000      2023.000000
75%        200.00000        350.000000      2024.000000
max        300.00000        400.000000      2025.000000

In [ ]:
#filter project with capacity greater than 100 MW
filtered_projects = projects_df[projects_df["Capacity (MW)"] > 100]

print("\nProjects with Capacity Greater than 100 MW:")
print(filtered_projects)


Projects with Capacity Greater than 100 MW:
          Project  Technology  Capacity (MW)  Cost (Million $)    Location  \
0    Solar Farm A       Solar            150               200  California   
1  Wind Turbine X        Wind            300               400       Texas   
2    Hydropower Y  Hydropower            200               350  Washington   

   Completion Year  
0             2023  
1             2024  
2             2022  


In [ ]:
#calculate cost per MW for each project and represent it in a new column
projects_df["Cost per MW"] = projects_df["Cost (Million $)"] / projects_df["Capacity (MW)"]

print("\nGreen Technology Projects Dataframe with Cost per MW:")
print(projects_df)


Green Technology Projects Dataframe with Cost per MW:
              Project  Technology  Capacity (MW)  Cost (Million $)  \
0        Solar Farm A       Solar            150               200   
1      Wind Turbine X        Wind            300               400   
2        Hydropower Y  Hydropower            200               350   
3        Solar Roof Z       Solar             50               100   
4  Geothermal Plant P  Geothermal            100               250   

     Location  Completion Year  Cost per MW  
0  California             2023     1.333333  
1       Texas             2024     1.333333  
2  Washington             2022     1.750000  
3      Nevada             2025     2.000000  
4       Idaho             2023     2.500000  


In [ ]:
#aggregate the total capacity and cost
total_capacity=projects_df["Capacity (MW)"].sum()
total_cost=projects_df["Cost (Million $)"].sum()

print(f"\nTotal Capacity of all projects: {total_capacity} MW")
print(f"Total Cost of all projects: {total_cost} Million $")


Total Capacity of all projects: 800 MW
Total Cost of all projects: 1300 Million $


In [ ]:
#group by "Technology" and calculate total capacity for each type
grouped_data = projects_df.groupby("Technology")["Capacity (MW)"].sum()

print("\nTotal Capacity by Technology:")
print(grouped_data)


Total Capacity by Technology:
Technology
Geothermal    100
Hydropower    200
Solar         200
Wind          300
Name: Capacity (MW), dtype: int64


In [ ]:
#numpy means numerical python
import numpy as np


In [ ]:
#one dimensional array
one_d_array = np.array([1,2,3,4,5])
print(one_d_array)


[1 2 3 4 5]


In [ ]:
#create two dimensional array
two_d_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(two_d_array)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


A numpy array has following attributes:
1.ndarray shape
2.ndarray.ndim
3.ndarray.size
5.ndarray.dtype
6.ndarray.itemsize

In [ ]:
print(two_d_array.shape)
print(two_d_array.ndim)
print(two_d_array.size)
print(two_d_array.dtype)
print(two_d_array.itemsize)

(3, 3)
2
9
int64
8


NumPy Vs List:

In [ ]:
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.random.random(3)

array([0.17026417, 0.14646539, 0.01057196])

In [ ]:
#to get an array with specified input element of desired shape
array = np.full((2,3),7)
print(array)


[[7 7 7]
 [7 7 7]]


In [ ]:
#write the code to get the identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#create an array with elements from 5 to 10 (exclusive)
#parameters for the functions -  np.arrange(start, stop, step, dtype)
array = np.arange(5,10)
print(array)

[5 6 7 8 9]


In [ ]:
linspace_array1= np.linspace(5,10,3)
print(linspace_array1)

[ 5.   7.5 10. ]


In [ ]:
linspace_array2 = np.linspace(2.0, 3.0, num=6,retstep = True)
print(linspace_array2)

(array([2. , 2.2, 2.4, 2.6, 2.8, 3. ]), 0.2)


In [ ]:
#accessing element in 1 d numpy array
data =  np.array([1,2,3,4,5])
print(data[0])
print(data[1])


1
2


In [ ]:
num_data = np.array([11, 22, 33, 44, 55, 66, 77, 88, 99])
print(num_data[:])
print(num_data[::1])
print(num_data[::2]) # start and stop parameters is unspecified, use step size = 2
print(num_data[::-1])  #print all elements in reverse order

[11 22 33 44 55 66 77 88 99]
[11 22 33 44 55 66 77 88 99]
[11 33 55 77 99]
[99 88 77 66 55 44 33 22 11]


In [ ]:
#write a code to check string is palindrone or not
string = input("Enter a string: ")
if string == string[::-1]:
    print("The string is a palindrome.")
else:
    print("The string is not a palindrome.")

Enter a string: 123454321
The string is a palindrome.


In [ ]:
#give code for reshaping the array using reshape function
data = np.array([1,2,3,4,5,6,7,8,9])
data.reshape(3,3)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#transpose
array=np.array([[1,2,3],[4,5,6]])
print(array.T)



[[1 4]
 [2 5]
 [3 6]]


In [ ]:
array = np.array([[1,2,3],[4,5,6]])
print(array.flatten())

[1 2 3 4 5 6]


In [ ]:
#calculating mean median and mode
data = np.array([1,2,3,4,5])
print(np.mean(data))
print(np.median(data))
print(np.std(data))

3.0
3.0
1.4142135623730951


In [ ]:
energy_consumption=np.array([1200,3400,2900,1800,2500])
print("Energy consumption (in Mwh) for different renewable sources")
print(energy_consumption)

#finding mean mode and median for the above
print("Mean energy consumption:",np.mean(energy_consumption))
print("Median energy consumption:",np.median(energy_consumption))
print("Standard deviation of energy consumption:",np.std(energy_consumption))

Energy consumption (in Mwh) for different renewable sources
[1200 3400 2900 1800 2500]
Mean energy consumption: 2360.0
Median energy consumption: 2500.0
Standard deviation of energy consumption: 781.2809993849844


In [ ]:
#reshaping the array
data = np.array([1,2,3,4,5,6,7,8,9])
data.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])